### ISSUE TITLE
the button "F" should be modified

### ISSUE THREAD

**Issue by ibrahimlis** [leonardo-ono/JavaSuperMarioBros#1]
When you press "F" button, it brings you to the end of the map (final destination)

**Comment by leonardo-ono** [comment]
ow, it's not a bug, it's actually something that i implemented for debugging purposes, as you can see here: https://github.com/leonardo-ono/JavaSuperMarioBros/blob/master/src/br/ol/smb/entity/Mario.java

private void updateDebug() {
...
...
...
if (Input.isKeyPressed(KeyEvent.VK_F)) {
getPosition().setX(195 * Map.TILE_SIZE);
camera.getPosition().setX(195 * Map.TILE_SIZE);
}
...
...
...

thanks anyway :)
